CREATE DATABASE Clinica_Vet;

USE Clinica_Vet;

CREATE TABLE Dono
(
idDono INT PRIMARY KEY IDENTITY,
Nome VARCHAR(200) NOT NULL,
CPF VARCHAR(200) NOT NULL,
);
CREATE TABLE Pets
(
idPet INT PRIMARY KEY IDENTITY,
IdDono INT FOREIGN KEY REFERENCES Dono (idDono),
Raça VARCHAR(200)NOT NULL,
Nome VARCHAR(200)NOT NULL,
Data_Nasc DATE NOT NULL,
Tipo_de_Pet VARCHAR(200),
);
CREATE TABLE Veterinarios
(
idVeterinario INT PRIMARY KEY IDENTITY,
idPet INT FOREIGN KEY REFERENCES Pets (idPet),
Nome VARCHAR(200)NOT NULL,
);

CREATE TABLE Clinica
(
idClinica INT PRIMARY KEY IDENTITY,
idVeterinario INT FOREIGN KEY REFERENCES Veterinarios (idVeterinario),
Endereço VARCHAR(200) NOT NULL,
);
