CREATE DATABASE Pessoas;

USE Pessoas;
  -- Criando tabela CNH
  CREATE TABLE CNH
  (
  idCNH INT PRIMARY KEY IDENTITY,
  Numero INT NOT NULL,
  );
  --Criando tabela de Pessoas
CREATE TABLE Pessoas (
  idPessoa INT PRIMARY KEY IDENTITY,
  idCNH INT FOREIGN KEY REFERENCES CNH (idCNH),
  Nome VARCHAR(200) NOT NULL,
  Telefone VARCHAR(200) NOT NULL,
  Email VARCHAR(200) NOT NULL,
  );
  --PARA FUNCIONAR, A TABLELA INDEPENDENTE DE QUALQUER OUTRA DEVE SER FEITA PRIMEIRO.
  --PARA EXECUTAR UM COMANDO ESPECÍFICO, DEVE-SE SELECIONÁ-LO.
  --NÃO EXECUTAR O COMANDO CREATE DATABASE DUAS OU MAIS VEZES.- CUIDADO!
